### ISSUE TITLE
Auto 1.6.0 issues

### ISSUE THREAD

**Issue by MaxLanc** [aria1th/stable-diffusion-webui-two-shot#1]
Hello! Thanks for maintaining latent couple!

I'm running the extension on auto 1.6.0 and its doesn't seem to work

The following error trace pops out and have confirmed the image splitting doesn't work, however rolling back to 2117fd9 works again
![imagen](https://github.com/aria1th/stable-diffusion-webui-two-shot/assets/95586248/cfdba8df-98f4-4da4-b398-fecbd76b26dd)

There are also these minor issues during startup
![imagen](https://github.com/aria1th/stable-diffusion-webui-two-shot/assets/95586248/b26972f6-aaf6-4e5e-b3a5-bdbce37a55a3)

Thanks a lot!

**Comment by aria1th** [comment]
@MaxLanc Thanks for the bug report! However, I found that it is somehow working as intended, but the UI has changed slightly:
![image](https://github.com/aria1th/stable-diffusion-webui-two-shot/assets/35677394/a66f6c2d-f0e6-4508-848e-c29544764ad4)
You might have to push the button manually and select the type of separation - to prevent gradio 'state' affecting the actual process.

Here is the prompt I used:
```
masterpiece
AND BREAK 1girl, red hair, schoolgirl uniform
AND BREAK grass and ponds
AND BREAK 1girl, blue hair, police uniform
```

![image](https://github.com/aria1th/stable-diffusion-webui-two-shot/assets/35677394/0f43ae86-f5a4-4f6e-8135-fcbe202ad7b5)

**Comment by MaxLanc** [comment]
So I click "I've finished sketch" and then I can switch to rect mode? I'm using that mode due to simplicity sake

**Comment by aria1th** [comment]
@MaxLanc 
yes - its for just dummy image-
(
![image](https://github.com/aria1th/stable-diffusion-webui-two-shot/assets/35677394/72ba2694-d10c-40fe-969b-3a4d87adbd8b)

![image](https://github.com/aria1th/stable-diffusion-webui-two-shot/assets/35677394/976a3c78-c934-4753-8704-3e693185b168)

prompt 
```
1girl, red hair, schoolgirl uniform
AND BREAK 1girl, blue hair, police uniform
```

**Comment by MaxLanc** [comment]
Thanks a lot, tested and confirm it works
Painted whatever on the mask mode, clicked apply and then changed to rect mode, all other changes to rect mode work normal without any other extra clicks

![tmpxv5dl93x](https://github.com/aria1th/stable-diffusion-webui-two-shot/assets/95586248/68fd1ff3-65e6-4908-8c5d-4a0784153afb)

![tmpprc9r2ot](https://github.com/aria1th/stable-diffusion-webui-two-shot/assets/95586248/e75e6654-02ab-4ebf-b466-073ebb5a01cb)

Prompts:

`lake background AND
2girls, blue hair AND
2girls, red hairr`

`lake background AND
2girls, blue hair AND
2girls, red hair AND
large tower`

Given this, I would suggest to add a small change to the repo's readme, adding this small workaround for people that get this bug

**Comment by aria1th** [comment]
@MaxLanc Still it is bug that it requires blank image - I added some workaround in recent commit, can you check it?

**Comment by MaxLanc** [comment]
@aria1th Nope, not fixed

Img using just latent couple:
![tmpacw9wc_5](https://github.com/aria1th/stable-diffusion-webui-two-shot/assets/95586248/99ec4e35-a04f-4874-b284-77cc05447fa5)

Img using the workaround from before in the same build as pic above:
![tmpvxglq1yb](https://github.com/aria1th/stable-diffusion-webui-two-shot/assets/95586248/7a88f147-f9b5-4f9b-ad72-ee56b7338766)

**Comment by aria1th** [comment]
@MaxLanc I fixed it again, it should work now (at least tested once) even without apply button, can you check it?

**Comment by MaxLanc** [comment]
@aria1th 
It werks

Pic gen'd using rect and lora mask
![grid-0008](https://github.com/aria1th/stable-diffusion-webui-two-shot/assets/95586248/d3b5eadf-6806-40fe-94de-53a3d5ff04cb)

Example without latent couple and only lora mask
![grid-0009](https://github.com/aria1th/stable-diffusion-webui-two-shot/assets/95586248/1c6138e7-f5a6-4aba-a0b7-b37ba00c48e0)

And finally example with only latent couple
![grid-0011](https://github.com/aria1th/stable-diffusion-webui-two-shot/assets/95586248/af07dabe-97e7-453d-8746-a8d2ae7beee0)

All where done same model, same 3 (one at zero weight) loras and prompt

Closing as completed, if I find something else will report back!

Thanks for the fix!
