### ISSUE TITLE
A1111 1.6.0 - Rect mode not working

### ISSUE THREAD

**Issue by MaxLanc** [aria1th/stable-diffusion-webui-two-shot#3]
Once again, Rect mode is broken
![61088095c31de7001849e5ea](https://github.com/aria1th/stable-diffusion-webui-two-shot/assets/95586248/2fb1c371-a2e5-4b9d-8e57-8b4438bb1508)

Hello and thanks for maintaining latent couple!
However it seems that rect mode is once again buggy, it works however after doing the same workaround of creating any image on mask mode and clicking "I've finished my sketch"

![imagen](https://github.com/aria1th/stable-diffusion-webui-two-shot/assets/95586248/9f4ee8c3-56a9-4238-a779-e0ae543cf69f)
Here be the error

**Comment by aria1th** [comment]
@MaxLanc  Yeah... I forgot to remove check when mode is Rect :notlikethis:
I'll fix this within 2 hours, thanks for the report!

**Comment by aria1th** [comment]
@MaxLanc The fix should fix the issue, please check it!

**Comment by MaxLanc** [comment]
@aria1th 
Tested and can confirm it werks, closing issue!

Thanks a lot!
